-- MySQL Script generated by MySQL Workbench
-- Sun Jun 12 00:48:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
  `movie_code` INT NOT NULL,
  `film_rate_kor` VARCHAR(45) NULL,
  `film_rate_foreign` VARCHAR(45) NULL,
  `story` VARCHAR(45) NULL,
  `makingnote` VARCHAR(45) NULL,
  `aka` VARCHAR(45) NULL,
  `title_kor` VARCHAR(45) NULL,
  `title_foregin` VARCHAR(45) NULL,
  `release` VARCHAR(45) NULL,
  `current_opening` VARCHAR(45) NULL,
  PRIMARY KEY (`movie_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mpeoole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mpeoole` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mpeoole` (
  `mpeoole_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `mpeople_code` VARCHAR(45) NULL,
  PRIMARY KEY (`mpeoole_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie_appearance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movie_appearance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movie_appearance` (
  `mpeoole_mpeoole_id` INT NOT NULL,
  `movie_movie_code` INT NOT NULL,
  PRIMARY KEY (`mpeoole_mpeoole_id`, `movie_movie_code`),
  CONSTRAINT `fk_movie_appearance_mpeoole`
    FOREIGN KEY (`mpeoole_mpeoole_id`)
    REFERENCES `mydb`.`mpeoole` (`mpeoole_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_appearance_movie1`
    FOREIGN KEY (`movie_movie_code`)
    REFERENCES `mydb`.`movie` (`movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_movie_appearance_mpeoole_idx` ON `mydb`.`movie_appearance` (`mpeoole_mpeoole_id` ASC) VISIBLE;

CREATE INDEX `fk_movie_appearance_movie1_idx` ON `mydb`.`movie_appearance` (`movie_movie_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.` quotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.` quotes` ;

CREATE TABLE IF NOT EXISTS `mydb`.` quotes` (
  `quotes_id` INT NOT NULL AUTO_INCREMENT,
  `movie_appearance_mpeoole_mpeoole_id` INT NOT NULL,
  `movie_appearance_movie_movie_code` INT NOT NULL,
  `quotes` VARCHAR(45) NULL,
  `good` INT NULL,
  PRIMARY KEY (`quotes_id`, `movie_appearance_mpeoole_mpeoole_id`, `movie_appearance_movie_movie_code`),
  CONSTRAINT `fk_ quotes_movie_appearance1`
    FOREIGN KEY (`movie_appearance_mpeoole_mpeoole_id` , `movie_appearance_movie_movie_code`)
    REFERENCES `mydb`.`movie_appearance` (`mpeoole_mpeoole_id` , `movie_movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ quotes_movie_appearance1_idx` ON `mydb`.` quotes` (`movie_appearance_mpeoole_mpeoole_id` ASC, `movie_appearance_movie_movie_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`casting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`casting` ;

CREATE TABLE IF NOT EXISTS `mydb`.`casting` (
  `casting_id` INT NOT NULL AUTO_INCREMENT,
  `movie_appearance_mpeoole_mpeoole_id` INT NOT NULL,
  `movie_appearance_movie_movie_code` INT NOT NULL,
  `casting_name` VARCHAR(45) NULL,
  PRIMARY KEY (`casting_id`, `movie_appearance_mpeoole_mpeoole_id`, `movie_appearance_movie_movie_code`),
  CONSTRAINT `fk_casting_movie_appearance1`
    FOREIGN KEY (`movie_appearance_mpeoole_mpeoole_id` , `movie_appearance_movie_movie_code`)
    REFERENCES `mydb`.`movie_appearance` (`mpeoole_mpeoole_id` , `movie_movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_casting_movie_appearance1_idx` ON `mydb`.`casting` (`movie_appearance_mpeoole_mpeoole_id` ASC, `movie_appearance_movie_movie_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`mpeople_sub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mpeople_sub` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mpeople_sub` (
  `mpeople_sub_id` INT NOT NULL AUTO_INCREMENT,
  `movie_movie_code` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `casting` VARCHAR(45) NULL,
  PRIMARY KEY (`mpeople_sub_id`, `movie_movie_code`),
  CONSTRAINT `fk_mpeople_sub_movie1`
    FOREIGN KEY (`movie_movie_code`)
    REFERENCES `mydb`.`movie` (`movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_mpeople_sub_movie1_idx` ON `mydb`.`mpeople_sub` (`movie_movie_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`relate_movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`relate_movie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`relate_movie` (
  `movie_movie_code` INT NOT NULL,
  `movie_movie_code1` INT NOT NULL,
  PRIMARY KEY (`movie_movie_code`, `movie_movie_code1`),
  CONSTRAINT `fk_movie_has_movie_movie1`
    FOREIGN KEY (`movie_movie_code`)
    REFERENCES `mydb`.`movie` (`movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_has_movie_movie2`
    FOREIGN KEY (`movie_movie_code1`)
    REFERENCES `mydb`.`movie` (`movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_movie_has_movie_movie2_idx` ON `mydb`.`relate_movie` (`movie_movie_code1` ASC) VISIBLE;

CREATE INDEX `fk_movie_has_movie_movie1_idx` ON `mydb`.`relate_movie` (`movie_movie_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `movie_movie_code` INT NOT NULL,
  `score` INT NULL,
  `conment` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `write_time` VARCHAR(45) NULL,
  `good` INT NULL,
  `bad` INT NULL,
  PRIMARY KEY (`comment_id`, `movie_movie_code`),
  CONSTRAINT `fk_score_movie1`
    FOREIGN KEY (`movie_movie_code`)
    REFERENCES `mydb`.`movie` (`movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_score_movie1_idx` ON `mydb`.`comment` (`movie_movie_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `movie_movie_code` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `view_num` INT NULL,
  `good` INT NULL,
  `date` VARCHAR(45) NULL,
  `writer` VARCHAR(45) NULL,
  PRIMARY KEY (`review_id`, `movie_movie_code`),
  CONSTRAINT `fk_review_movie1`
    FOREIGN KEY (`movie_movie_code`)
    REFERENCES `mydb`.`movie` (`movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_review_movie1_idx` ON `mydb`.`review` (`movie_movie_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`score` ;

CREATE TABLE IF NOT EXISTS `mydb`.`score` (
  `score_id` INT NOT NULL AUTO_INCREMENT,
  `movie_movie_code` INT NOT NULL,
  `score` DOUBLE NULL,
  `type` VARCHAR(45) NULL,
  `comment_number` INT NULL,
  PRIMARY KEY (`score_id`, `movie_movie_code`),
  CONSTRAINT `fk_score_movie2`
    FOREIGN KEY (`movie_movie_code`)
    REFERENCES `mydb`.`movie` (`movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_score_movie2_idx` ON `mydb`.`score` (`movie_movie_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`review_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`review_comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`review_comment` (
  `reviewcomment_id` INT NOT NULL AUTO_INCREMENT,
  `review_review_id` INT NOT NULL,
  `review_movie_movie_code` INT NOT NULL,
  `writer` VARCHAR(45) NULL,
  `good` INT NULL,
  `bad` INT NULL,
  `comment` VARCHAR(45) NULL,
  `write_time` VARCHAR(45) NULL,
  PRIMARY KEY (`reviewcomment_id`, `review_review_id`, `review_movie_movie_code`),
  CONSTRAINT `fk_review_comment_review1`
    FOREIGN KEY (`review_review_id` , `review_movie_movie_code`)
    REFERENCES `mydb`.`review` (`review_id` , `movie_movie_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_review_comment_review1_idx` ON `mydb`.`review_comment` (`review_review_id` ASC, `review_movie_movie_code` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
